"""
RakshakAI Hallucination Guard
A callable safety module reachable from Screening, Retrieval, and Verification agents.
Guarantees that ungrounded, contradictory, or unverified legal statements never reach the end user.
"""

FALLBACK_MESSAGE = (
    "SAFETY_FALLBACK: Unable to verify clause compliance against official statutory provisions "
    "with required confidence. Please consult a qualified legal advisor or official regulator."
)

def trigger_hallucination_fallback(reason: str = "Unverified statutory grounding", stage: str = "Unknown") -> dict:
    """
    Returns a standardized safety fallback payload when grounding or verification fails.
    """
    return {
        "verdict": "FLAGGED_FOR_HUMAN_REVIEW",
        "status": "FALLBACK",
        "risk_level": "High-risk (Unverified)",
        "citation": "N/A - Safety Guard Triggered",
        "explanation": FALLBACK_MESSAGE,
        "disclaimer": "This output was flagged by RakshakAI Hallucination Guard to prevent unverified legal claims. Not legal advice.",
        "hallucination_guard_triggered": True,
        "trigger_reason": reason,
        "trigger_stage": stage,
        "needs_human_review": True
    }

def validate_statutory_grounding(extracted_citations: list, retrieved_context: str) -> bool:
    """
    Checks if citations generated by reasoning or verification are genuinely present in the retrieved statutory corpus.
    """
    if not extracted_citations:
        return False
    context_lower = retrieved_context.lower()
    for citation in extracted_citations:
        if str(citation).lower().strip() in context_lower:
            return True
    return False
