"""
RakshakAI Reasoning Agent
Powered by Gemini Flash.
Synthesizes verified legal context into actionable, structured legal intelligence:
- Verdict (RED / YELLOW / GREEN)
- Statutory Citation
- Explanation of Worker/Borrower Harm
- Statutory Disclaimer
"""

import os
import json
import logging
from dotenv import load_dotenv
from google import genai

load_dotenv()
logger = logging.getLogger("RakshakAI.ReasoningAgent")

class ReasoningAgent:
    def __init__(self):
        self.api_key = os.getenv("GEMINI_API_KEY")
        self.client = None
        self.model_name = "gemini-3.6-flash"
        if self.api_key:
            try:
                self.client = genai.Client(api_key=self.api_key)
                logger.info("[+] Reasoning Agent initialized with Gemini Flash.")
            except Exception as e:
                logger.error(f"[-] Failed to initialize Gemini client: {e}")

    def reason(self, clause_text: str, retrieved_provisions: list[dict], verification_result: dict) -> dict:
        """
        Synthesizes final verdict, citation, explanation, and disclaimer using Gemini Flash.
        """
        statutory_context = "\n\n".join([
            f"Statute: {p['act']}\nSection: {p['section']}\nText: {p['text']}"
            for p in retrieved_provisions
        ])

        if self.client is None:
            # Fallback deterministic synthesis
            matched_sec = verification_result.get("matched_section", retrieved_provisions[0]["section"])
            matched_act = verification_result.get("matched_statute", retrieved_provisions[0]["act"])
            return {
                "verdict": "RED" if verification_result.get("violation_detected", True) else "GREEN",
                "risk_level": "High-risk" if verification_result.get("violation_detected", True) else "Low-risk",
                "citation": f"{matched_act} - {matched_sec}",
                "explanation": f"Clause violates provisions of {matched_act} ({matched_sec}).",
                "disclaimer": "Automated legal compliance screening by RakshakAI. Does not constitute formal attorney-client advice.",
                "recommendation": "Flag this clause or request removal before signing.",
                "needs_human_review": False
            }

        prompt = f"""You are RakshakAI, India's AI Legal Shield against predatory contracts and illegal loan apps.
Analyze the following clause based on the verified legal provisions.

Clause:
\"\"\"{clause_text}\"\"\"

Verified Legal Context:
\"\"\"{statutory_context}\"\"\"

Verification Judge Verdict:
{json.dumps(verification_result, indent=2)}

Instructions:
1. Assign a clear Verdict:
   - "RED" if the clause is illegal, unconscionable, predatory, or violates statutory provisions.
   - "YELLOW" if the clause is borderline, vague, or creates a moderate imbalance.
   - "GREEN" if the clause is compliant, fair, or standard.
2. Provide exact Statutory Citation (e.g., 'DPDP Act 2023 §6(1)', 'RBI Digital Lending Guidelines 2022 Cl. 5', 'Karnataka Gig Worker Act 2025').
3. Write a clear, accessible 2-3 sentence Explanation detailing why this clause harms the worker/borrower or violates the law.
4. Include an Actionable Recommendation for the user.
5. Standard legal Disclaimer.

Respond ONLY in valid JSON matching this exact structure:
{{
  "verdict": "RED",
  "risk_level": "High-risk",
  "citation": "Exact section citation",
  "explanation": "Clear 2-3 sentence legal breakdown",
  "recommendation": "What the user should do",
  "disclaimer": "This analysis is generated by RakshakAI for consumer awareness and does not constitute formal legal counsel under the Advocates Act 1961."
}}
"""

        try:
            response = self.client.models.generate_content(
                model=self.model_name,
                contents=prompt
            )
            raw_text = response.text.strip()
            if raw_text.startswith("```json"):
                raw_text = raw_text[7:]
            if raw_text.startswith("```"):
                raw_text = raw_text[3:]
            if raw_text.endswith("```"):
                raw_text = raw_text[:-3]

            data = json.loads(raw_text.strip())
            logger.info(f"[Reasoning] Verdict synthesized: {data.get('verdict')} | Citation: {data.get('citation')}")
            return data

        except Exception as e:
            logger.error(f"[-] Reasoning agent generation error: {e}")
            matched_sec = verification_result.get("matched_section", retrieved_provisions[0]["section"])
            matched_act = verification_result.get("matched_statute", retrieved_provisions[0]["act"])
            return {
                "verdict": "RED" if verification_result.get("violation_detected", True) else "GREEN",
                "risk_level": "High-risk",
                "citation": f"{matched_act} ({matched_sec})",
                "explanation": f"The clause imposes non-compliant terms violating {matched_act}.",
                "recommendation": "Do not accept without negotiating fair terms or consulting an advocate.",
                "disclaimer": "RakshakAI automated legal awareness output. Not legal advice."
            }

reasoning_agent = ReasoningAgent()
